#!/bin/sh

set -e

root=$(cd "$(dirname $0)"/.. && pwd)

echo "Bundling..."
script/bootstrap

ruby -I"${root}/test" -e \
  "(ARGV.empty? ? Dir['${root}/test/**/*_test.rb'] : ARGV).each { |f| load f }"
